//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtCO9T1Twitter39URTHomeConversationTreeIndentationRules18TreeBuilderContext : _TtCs12_SwiftObject
{
    // Error parsing type: , name: statusByIDString
    // Error parsing type: , name: nodeToIndentation
    // Error parsing type: , name: nodeToRenderContext
    // Error parsing type: , name: branchNodes
    // Error parsing type: , name: nodeRenderContextCollection
}

@end

