//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/T1ContentStreamingSubscriptionEntryDelegate-Protocol.h>

@class T1ContentStreamingSubscriptionEntry, TFSTwitterTweetSubscriptionEvent;

@protocol T1ContentStreamingSubscriptionHomeTimelineEntryDelegate <T1ContentStreamingSubscriptionEntryDelegate>
- (void)contentStreamingSubscriptionEntry:(T1ContentStreamingSubscriptionEntry *)arg1 didReceiveTweetSubscriptionEvent:(TFSTwitterTweetSubscriptionEvent *)arg2;
@end

