//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/T1ContentStreamingSubscriptionEntry.h>

@class NSDate, NSMutableArray;
@protocol T1ContentStreamingSubscriptionHomeTimelineEntryDelegate;

@interface T1ContentStreamingSubscriptionHomeTimelineEntry : T1ContentStreamingSubscriptionEntry
{
    NSDate *_lastUpdated;
    unsigned long long _entryType;
    id <T1ContentStreamingSubscriptionHomeTimelineEntryDelegate> _delegate;
    NSMutableArray *_statusIDNumberArray;
    NSDate *_lastRefresh;
}

+ (id)defaultIdentifier;
@property(retain, nonatomic) NSDate *lastRefresh; // @synthesize lastRefresh=_lastRefresh;
@property(readonly, nonatomic) NSMutableArray *statusIDNumberArray; // @synthesize statusIDNumberArray=_statusIDNumberArray;
@property(nonatomic) __weak id <T1ContentStreamingSubscriptionHomeTimelineEntryDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned long long entryType; // @synthesize entryType=_entryType;
@property(retain, nonatomic) NSDate *lastUpdated; // @synthesize lastUpdated=_lastUpdated;
- (void).cxx_destruct;
- (void)_t1_parseTweetSubscriptionEvent:(id)arg1;
- (void)_t1_parseSubscriptionStatusPayload:(id)arg1;
- (void)subscription:(id)arg1 didReceiveEvent:(id)arg2;
- (id)initWithTopic:(id)arg1 account:(id)arg2;

@end

