//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/TLPSubscriptionDelegate-Protocol.h>

@class NSDate, NSString, TFNTwitterAccount, TLPSubscription;
@protocol T1ContentStreamingSubscriptionEntryDelegate;

@interface T1ContentStreamingSubscriptionEntry : NSObject <TLPSubscriptionDelegate>
{
    TFNTwitterAccount *_account;
    TLPSubscription *_subscription;
    NSString *_topic;
    unsigned long long _entryType;
    NSDate *_lastUpdated;
    double _backoffTimeInterval;
    id <T1ContentStreamingSubscriptionEntryDelegate> _delegate;
}

+ (id)defaultIdentifier;
@property(nonatomic) __weak id <T1ContentStreamingSubscriptionEntryDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) double backoffTimeInterval; // @synthesize backoffTimeInterval=_backoffTimeInterval;
@property(retain, nonatomic) NSDate *lastUpdated; // @synthesize lastUpdated=_lastUpdated;
@property(readonly, nonatomic) unsigned long long entryType; // @synthesize entryType=_entryType;
@property(readonly, copy, nonatomic) NSString *topic; // @synthesize topic=_topic;
@property(readonly, nonatomic) TLPSubscription *subscription; // @synthesize subscription=_subscription;
@property(readonly, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (void)subscription:(id)arg1 didReceiveEvent:(id)arg2;
@property(readonly, copy, nonatomic) NSString *cacheIdentifier;
- (id)initWithTopic:(id)arg1 account:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

