//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface T1ContentStreamingSubscriptionCache : NSObject
{
    NSMutableDictionary *_cache;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableDictionary *cache; // @synthesize cache=_cache;
- (void).cxx_destruct;
- (void)clear;
- (void)removeSubscriptionWithIdentifier:(id)arg1;
- (void)addSubscriptionEntry:(id)arg1 identifier:(id)arg2 shouldReplace:(_Bool)arg3;
- (id)subscriptionEntryWithIdentifier:(id)arg1;
- (id)livePipelineSubscriptionWithIdentifier:(id)arg1;
- (id)livePipelineSubscriptions;
- (id)init;

@end

