//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNViewController.h>

@class T1ShowStatusNavigationContext, T1URTViewController, TFNTwitterAccount;
@protocol T1StatusViewModel;

@interface T1ConversationContainerViewController : TFNViewController
{
    long long _statusID;
    TFNTwitterAccount *_account;
    id <T1StatusViewModel> _viewModel;
    T1ShowStatusNavigationContext *_statusNavigationContext;
    T1URTViewController *_conversationTimelineViewController;
}

@property(retain, nonatomic) T1URTViewController *conversationTimelineViewController; // @synthesize conversationTimelineViewController=_conversationTimelineViewController;
@property(retain, nonatomic) T1ShowStatusNavigationContext *statusNavigationContext; // @synthesize statusNavigationContext=_statusNavigationContext;
@property(retain, nonatomic) id <T1StatusViewModel> viewModel; // @synthesize viewModel=_viewModel;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
@property(nonatomic) long long statusID; // @synthesize statusID=_statusID;
- (void).cxx_destruct;
- (void)_t1_showTweetAnalyticsForStatus:(id)arg1;
- (void)_t1_toggleFavoriteOnCurrentStatus:(id)arg1;
- (id)_t1_favoriteConfirmMenuSheetForStatus:(id)arg1;
- (void)_t1_showRetweetIntentConfirmationForStatus:(id)arg1;
- (void)_t1_showFavoriteIntentConfirmationForStatus:(id)arg1;
- (void)_t1_handleStatusShowNavigationContext;
- (void)viewDidLoad;
- (id)initWithViewModel:(id)arg1 account:(id)arg2 statusNavigationContext:(id)arg3;
- (id)initWithStatusID:(long long)arg1 account:(id)arg2 statusNavigationContext:(id)arg3;

@end

