//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/T1ContentStreamingSubscriptionEntryDelegate-Protocol.h>
#import <T1Twitter/T1ContentStreamingSubscriptionHomeTimelineEntryDelegate-Protocol.h>
#import <T1Twitter/UIScrollViewDelegate-Protocol.h>

@class NSString, T1ContentStreamingHomeTimelineSubscribeTask, T1DataViewControllerLoadTopTask, TFNDataViewController, TFNTwitterAccount, TFSTwitterRecurringTaskTimerEventSource, TLPClient;
@protocol T1ContentStreamingSubscriptionManagerDelegate, TNUNetworkQualityProvider;

@interface T1ContentStreamingSubscriptionManager : NSObject <T1ContentStreamingSubscriptionEntryDelegate, T1ContentStreamingSubscriptionHomeTimelineEntryDelegate, UIScrollViewDelegate>
{
    _Bool _nextUpdateShouldScrollToTop;
    TFNDataViewController *_dataViewController;
    id <T1ContentStreamingSubscriptionManagerDelegate> _delegate;
    TFNTwitterAccount *_account;
    id <TNUNetworkQualityProvider> _networkQualityProvider;
    TLPClient *_livePipelineClient;
    T1DataViewControllerLoadTopTask *_dataViewControllerRefreshTask;
    TFSTwitterRecurringTaskTimerEventSource *_dataViewControllerRefreshTaskEventSource;
    T1ContentStreamingHomeTimelineSubscribeTask *_homeTimelineStreamingSubscribeTask;
    unsigned long long _modeType;
}

@property(nonatomic) unsigned long long modeType; // @synthesize modeType=_modeType;
@property(retain, nonatomic) T1ContentStreamingHomeTimelineSubscribeTask *homeTimelineStreamingSubscribeTask; // @synthesize homeTimelineStreamingSubscribeTask=_homeTimelineStreamingSubscribeTask;
@property(retain, nonatomic) TFSTwitterRecurringTaskTimerEventSource *dataViewControllerRefreshTaskEventSource; // @synthesize dataViewControllerRefreshTaskEventSource=_dataViewControllerRefreshTaskEventSource;
@property(retain, nonatomic) T1DataViewControllerLoadTopTask *dataViewControllerRefreshTask; // @synthesize dataViewControllerRefreshTask=_dataViewControllerRefreshTask;
@property(retain, nonatomic) TLPClient *livePipelineClient; // @synthesize livePipelineClient=_livePipelineClient;
@property(retain, nonatomic) id <TNUNetworkQualityProvider> networkQualityProvider; // @synthesize networkQualityProvider=_networkQualityProvider;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
@property(nonatomic) __weak id <T1ContentStreamingSubscriptionManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) __weak TFNDataViewController *dataViewController; // @synthesize dataViewController=_dataViewController;
- (void).cxx_destruct;
- (void)_t1_stopLivePipelineTracking;
- (void)_t1_stopLivePipelineTrackingSubscriptions:(id)arg1;
- (void)_t1_startLivePipelineTrackingSubscriptions:(id)arg1;
- (void)_t1_stopLivePipelineTrackingSubscriptionsWithIdentifier:(id)arg1;
- (void)_t1_startLivePipelineTrackingSubscriptionsWithIdentifier:(id)arg1 entryType:(unsigned long long)arg2;
- (void)_t1_initializeLivePipelineSubscribeTaskWithAccount:(id)arg1;
- (void)_t1_stopPolling;
- (void)_t1_startPolling;
- (void)_t1_stopTrackingSubscriptionsWithIdentifier:(id)arg1;
- (void)_t1_startTrackingSubscriptionsWithIdentifier:(id)arg1 entryType:(unsigned long long)arg2;
- (_Bool)_t1_canStartTracking;
- (unsigned long long)_t1_defaultRefreshCountThreshold;
- (double)_t1_defaultMinimumRefreshInterval;
- (double)_t1_defaultBackoffRenewInterval;
- (void)_t1_refreshRealTimeStreamingState;
- (void)_t1_featureSwitchesDidUpdate:(id)arg1;
- (void)contentStreamingSubscriptionEntryResetCache:(id)arg1;
- (void)contentStreamingSubscriptionEntry:(id)arg1 didReceiveTweetSubscriptionEvent:(id)arg2;
- (void)contentStreamingSubscriptionEntry:(id)arg1 didReceiveSubscriptionStatus:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
@property(readonly, nonatomic) _Bool flashesScrollIndicatorsOnUpdate;
@property(readonly, nonatomic, getter=isRealTimeStreamingEnabled) _Bool realTimeStreamingEnabled;
@property(readonly, nonatomic, getter=isSubscribedToTimelineUpdates) _Bool subscribedToTimelineUpdates;
- (void)updateTableViewScrollPosition;
@property(readonly, nonatomic) _Bool needsTableViewScrollPositionUpdate;
- (void)streamDidUpdateWithSource:(long long)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithAccount:(id)arg1 dataViewController:(id)arg2 livePipelineClient:(id)arg3 networkQualityProvider:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

