//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/TFSTwitterRecurringTask-Protocol.h>

@class NSString, TFNTwitterAccount;

@interface T1ContentStreamingHomeTimelineSubscribeTask : NSObject <TFSTwitterRecurringTask>
{
    // Error parsing type: AB, name: _isExecuting
    TFNTwitterAccount *_account;
    CDUnknownBlockType _completionBlock;
}

@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (id)tfs_errorDomain;
- (id)tfs_taskState;
- (void)tfs_triggerFromService:(id)arg1 event:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_t1_setExecuting:(_Bool)arg1;
@property(readonly, nonatomic, getter=isExecuting) _Bool executing;
- (id)initWithAccount:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

