//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/TFSTwitterRecurringTask-Protocol.h>

@class NSString, TFNDataViewController, TFNTwitterAccount;

@interface T1DataViewControllerLoadTopTask : NSObject <TFSTwitterRecurringTask>
{
    // Error parsing type: AB, name: _isExecuting
    TFNDataViewController *_dataViewController;
    NSString *_timelineIdentifier;
    TFNTwitterAccount *_account;
    CDUnknownBlockType _completionBlock;
}

@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
@property(copy, nonatomic) NSString *timelineIdentifier; // @synthesize timelineIdentifier=_timelineIdentifier;
@property(readonly, nonatomic) __weak TFNDataViewController *dataViewController; // @synthesize dataViewController=_dataViewController;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (void)_t1_updateLoadingTop;
- (id)tfs_errorDomain;
- (id)tfs_taskState;
- (void)tfs_triggerFromService:(id)arg1 event:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_t1_setExecuting:(_Bool)arg1;
@property(readonly, nonatomic, getter=isExecuting) _Bool executing;
- (id)initWithDataViewController:(id)arg1 timelineIdentifier:(id)arg2 account:(id)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

