//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

__attribute__((visibility("hidden")))
@interface T1DirectMessageReactionsButton : UIButton
{
    // Error parsing type: , name: reactionsConfiguration
    // Error parsing type: , name: reactionKey
    // Error parsing type: , name: isSelectedKey
    // Error parsing type: , name: handler
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)didReceiveTap:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

