//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFNFormViewController.h>

@class NSString, T1EnterPhoneNumberForm;
@protocol T1EnterPhoneNumberViewControllerDelegate, T1OnboardingHeaderViewModel;

@interface T1EnterPhoneNumberViewController : TFNFormViewController
{
    id <T1OnboardingHeaderViewModel> _headerItem;
    id <T1EnterPhoneNumberViewControllerDelegate> _delegate;
    NSString *_title;
    NSString *_subtitle;
    NSString *_nextLabel;
    NSString *_skipLabel;
    T1EnterPhoneNumberForm *_enterPhoneNumberForm;
}

- (void).cxx_destruct;
- (void)private_skipTapped:(id)arg1;
- (void)private_nextTapped:(id)arg1;
- (id)doneBarButtonItem;
- (_Bool)addsDoneBarButtonButtonItemToNavigationBar;
- (struct CGRect)additionalGutterFrame;
- (void)setSections:(id)arg1;
- (long long)tfn_preferredToolbarVisibility;
- (_Bool)tfn_prefersNavigationBarShadowHidden;
- (_Bool)tfn_logoTitleViewShown;
- (id)toolbarItems;
- (void)viewDidLoad;
- (id)initWithTitle:(id)arg1 subtitle:(id)arg2 nextLabel:(id)arg3 skipLabel:(id)arg4 hintText:(id)arg5 countryCodes:(id)arg6 defaultCountryCode:(id)arg7 discoverabilitySettingsTitle:(id)arg8 discoverabilitySettingsValue:(_Bool)arg9 delegate:(id)arg10;

@end

