//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/T1SpheresUserPinnedListsRepositoryDelegate-Protocol.h>

@class NSString, T1HomeTimelineSegmentedViewController, T1SpheresUserPinnedListsRepository, TFNTwitterAccount;

@interface T1HomeTimelineVariantCoordinator : NSObject <T1SpheresUserPinnedListsRepositoryDelegate>
{
    _Bool _isLatestSwitchEnabled;
    _Bool _timelineLoadingAfterManualSwitch;
    _Bool _appNavigationUpdateRequestEnabled;
    double _mostRecentAutoSwitchThreshold;
    double _mostRecentAutoSwitchInactiveTime;
    T1HomeTimelineSegmentedViewController *_delegate;
    unsigned long long _maxUserOwnedOrSubscribedLists;
    TFNTwitterAccount *_account;
    // Error parsing type: {?="lock"{os_unfair_lock_s="_os_unfair_lock_opaque"I}"predicate"{atomic_flag="_Value"AB}}, name: _defaultMigrationTransientDispatchOnceToken
    NSString *_segmentedControllerTreatment;
    T1SpheresUserPinnedListsRepository *_archiver;
}

+ (_Bool)_t1_containsListID:(id)arg1 inUserLists:(id)arg2;
@property(readonly, nonatomic) T1SpheresUserPinnedListsRepository *archiver; // @synthesize archiver=_archiver;
@property(readonly, nonatomic) _Bool appNavigationUpdateRequestEnabled; // @synthesize appNavigationUpdateRequestEnabled=_appNavigationUpdateRequestEnabled;
@property(readonly, nonatomic) NSString *segmentedControllerTreatment; // @synthesize segmentedControllerTreatment=_segmentedControllerTreatment;
// Error parsing type for property defaultMigrationTransientDispatchOnceToken:
// Property attributes: T{?={os_unfair_lock_s=I}{atomic_flag=AB}},R,N,V_defaultMigrationTransientDispatchOnceToken

@property(readonly, nonatomic) __weak TFNTwitterAccount *account; // @synthesize account=_account;
@property(readonly, nonatomic) unsigned long long maxUserOwnedOrSubscribedLists; // @synthesize maxUserOwnedOrSubscribedLists=_maxUserOwnedOrSubscribedLists;
@property(nonatomic) __weak T1HomeTimelineSegmentedViewController *delegate; // @synthesize delegate=_delegate;
- (void)setTimelineLoadingAfterManualSwitch:(_Bool)arg1;
- (_Bool)isTimelineLoadingAfterManualSwitch;
- (double)mostRecentAutoSwitchInactiveTime;
- (double)mostRecentAutoSwitchThreshold;
- (_Bool)isLatestSwitchEnabled;
- (void).cxx_destruct;
- (void)spheresUserPinnedListsCacheMissForRepository:(id)arg1;
- (void)spheresUserPinnedListsDidChangeForRepository:(id)arg1;
- (void)_t1_userDidAddUserToList:(id)arg1;
- (_Bool)isAppNavigationUpdateRequestEnabled;
- (void)_t1_removeListIDFromUserLists:(id)arg1;
- (void)_t1_userDidUpdateList:(id)arg1;
- (void)_t1_userUnsubscribedFromList:(id)arg1;
- (void)_t1_userDidDeleteList:(id)arg1;
- (void)navigateToTimelineAtIndex:(long long)arg1;
- (id)_t1_unarchiveSphereViewModels;
- (void)_t1_archiveSphereViewModels:(id)arg1;
- (id)_t1_paginatedResultsToList:(id)arg1;
- (void)setUserOwnedListsTimelines:(id)arg1;
- (id)userOwnedListsTimelines;
- (_Bool)_tfn_switchToTopTimePastThreshold:(double)arg1;
- (_Bool)shouldResetToTopTimeline;
- (void)processManualSwitchAfterAutoSwitchWithDelay:(double)arg1;
- (void)_tfn_processLatestTimelineFrustrationEvent;
- (double)_tfn_latestTimelineProgressiveAutoSwitchTimeThresholdComputedUsingMinThreshold:(double)arg1 halfLife:(double)arg2 lastFrustrationEventTime:(double)arg3 lastCheckedAutoSwitchThreshold:(double)arg4 currentTime:(double)arg5;
- (double)_tfn_latestTimelineProgressiveAutoSwitchComputedTimeThreshold;
- (double)_tfn_latestTimelineMostRecentProgressiveAutoSwitchThreshold;
- (double)_tfn_latestTimelineMostRecentFrustrationEventTime;
- (double)_tfn_timestampForLatestTimeline;
- (void)saveTimestampForLatestTimelineUpdate;
- (void)_tfn_clearTimestampForLatestTimeline;
- (void)clearInitialDefaultToHome;
- (_Bool)isInitialDefaultToHome;
- (void)setLatestHomeTimelineActive:(_Bool)arg1;
- (_Bool)isLatestHomeTimelineActive;
- (id)_tfn_legacy_isLatestHomeTimelineActiveKey;
- (void)_t1_migrateLegacyUserDefaults;
- (_Bool)isCondensedSegmentsHomeTimelinesEnabled;
- (_Bool)isSegmentedHomeTimelinesEnabled;
- (_Bool)isMultipleHomeTimelinesEnabled;
- (id)initWithAccount:(id)arg1 latestSwitchEnabled:(_Bool)arg2 segmentedControllerTreatment:(id)arg3 maxUserOwnedOrSubscribedLists:(long long)arg4 appNavigationUpdateRequestEnabled:(_Bool)arg5;

@end

