//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class T1NewsCameraCapturePreviewOverlayGradientView, T1NewsCameraDraggingHandleView;

@interface T1NewsCameraCapturePreviewOverlayView : UIView
{
    T1NewsCameraCapturePreviewOverlayGradientView *_gradientView;
    T1NewsCameraDraggingHandleView *_handleView;
}

@property(readonly, nonatomic) T1NewsCameraDraggingHandleView *handleView; // @synthesize handleView=_handleView;
@property(readonly, nonatomic) T1NewsCameraCapturePreviewOverlayGradientView *gradientView; // @synthesize gradientView=_gradientView;
- (void).cxx_destruct;
- (void)_t1_cameraCapturePreviewOverlayView_initialize;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

