//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/NSObject-Protocol.h>

@class NSArray, NSString, T1OnboardingSettingsListViewController, TFNOnboardingNavigationLink, TFNOnboardingRichText;

@protocol T1OnboardingSettingsListViewControllerDelegate <NSObject>

@optional
- (NSString *)settingsListViewController:(T1OnboardingSettingsListViewController *)arg1 expandedRichText:(TFNOnboardingRichText *)arg2;
- (void)settingsListViewController:(T1OnboardingSettingsListViewController *)arg1 didUpdateSettings:(NSArray *)arg2;
- (void)settingsListViewController:(T1OnboardingSettingsListViewController *)arg1 didTapNavigationLink:(TFNOnboardingNavigationLink *)arg2;
- (void)settingsListViewController:(T1OnboardingSettingsListViewController *)arg1 didTapAgreeWithSettings:(NSArray *)arg2;
@end

