//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNItemsDataViewController.h>

#import <T1Twitter/T1OnboardingSettingsListViewControllerDelegate-Protocol.h>
#import <T1Twitter/T1OnboardingSettingsValueViewModelDelegate-Protocol.h>
#import <T1Twitter/TFNPickerViewControllerDelegate-Protocol.h>
#import <T1Twitter/TFNPillControlDelegate-Protocol.h>
#import <T1Twitter/UIScrollViewDelegate-Protocol.h>

@class NSArray, NSString, TFNPeopleDiscoveryShowMore, TFNPillControl, TFNTwitterAccount;
@protocol T1OnboardingSettingsListViewControllerDelegate;

@interface T1OnboardingSettingsListViewController : TFNItemsDataViewController <UIScrollViewDelegate, T1OnboardingSettingsValueViewModelDelegate, TFNPillControlDelegate, T1OnboardingSettingsListViewControllerDelegate, TFNPickerViewControllerDelegate>
{
    id <T1OnboardingSettingsListViewControllerDelegate> _delegate;
    id _headerItem;
    NSString *_title;
    NSString *_subtitle;
    NSString *_agreeLabel;
    NSString *_detailText;
    NSArray *_detailEntities;
    NSString *_scrollHint;
    NSArray *_settings;
    NSArray *_viewModels;
    TFNTwitterAccount *_account;
    TFNPillControl *_pillControl;
    TFNPeopleDiscoveryShowMore *_showMore;
    unsigned long long _showMoreTapCount;
    _Bool _didReachEnd;
    _Bool _shouldDisplayCellBorders;
    _Bool _shouldShowTitleInNavigationBar;
}

@property(nonatomic) _Bool shouldShowTitleInNavigationBar; // @synthesize shouldShowTitleInNavigationBar=_shouldShowTitleInNavigationBar;
- (void).cxx_destruct;
- (id)private_expandedRichText:(id)arg1;
- (void)private_dataViewItemsForViewModels:(id)arg1 detailText:(id)arg2 detailEntities:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (unsigned long long)private_itemsToShow;
- (id)private_viewModelsForAccount:(id)arg1 settings:(id)arg2;
- (id)private_toolbarItemsWithAgreeLabel:(id)arg1;
- (void)private_updateSections;
- (void)private_nextTapped:(id)arg1;
- (void)private_updateToolbarWaiting:(_Bool)arg1;
- (id)private_viewModelForChoiceValue:(id)arg1;
- (void)pillControlTapped:(id)arg1;
- (void)update:(_Bool)arg1;
- (void)pickerViewControllerDidDismiss:(id)arg1;
- (void)pickerViewController:(id)arg1 didPickValue:(id)arg2 inSectionAtIndex:(unsigned long long)arg3 willConfirm:(_Bool)arg4 willDismiss:(_Bool)arg5;
- (void)settingsListViewController:(id)arg1 didUpdateSettings:(id)arg2;
- (void)onboardingSettingsValueViewModel:(id)arg1 didSelectListWithAcceptedValues:(id)arg2 isSearchEnabled:(_Bool)arg3;
- (void)onboardingSettingsValueViewModel:(id)arg1 didSelectBooleanWithSettingsValue:(id)arg2 booleanData:(_Bool)arg3;
- (void)onboardingSettingsValueViewModel:(id)arg1 didSelectSettingsGroupWithSettingsValues:(id)arg2 forSettingsValue:(id)arg3;
- (void)onboardingSettingsValueViewModel:(id)arg1 didSelectNavigationLinkWithLink:(id)arg2;
- (id)onboardingSettingsValueViewModel:(id)arg1 expandedRichText:(id)arg2;
- (void)onboardingSettingsValueViewModel:(id)arg1 didChangeForSettingsValue:(id)arg2;
- (void)scrollViewDidProgrammaticallyScrollToBottom:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)private_updatePillVisibility;
- (void)private_updatePillPosition;
- (double)private_presentationOffset;
- (long long)tfn_preferredToolbarVisibility;
- (_Bool)tfn_logoTitleViewShown;
- (_Bool)tfn_prefersNavigationBarShadowHidden;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewDidLayoutSubviews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithAccount:(id)arg1 settings:(id)arg2 title:(id)arg3 subtitle:(id)arg4 detailText:(id)arg5 detailEntities:(id)arg6 agreeLabel:(id)arg7 scrollHint:(id)arg8 showMore:(id)arg9 shouldDisplayCellBorders:(_Bool)arg10 delegate:(id)arg11;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

