//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/T1FlexibleLayoutView.h>

@protocol T1OnboardingTopicViewDelegate;

@interface T1OnboardingTopicView : T1FlexibleLayoutView
{
    id <T1OnboardingTopicViewDelegate> _delegate;
    id _userInfo;
}

@property(readonly, nonatomic) id userInfo; // @synthesize userInfo=_userInfo;
- (void).cxx_destruct;
- (void)private_buttonAction:(id)arg1;
- (id)initWithTitle:(id)arg1 subtitle:(id)arg2 selectLabel:(id)arg3 deselectLabel:(id)arg4 selected:(_Bool)arg5 userInfo:(id)arg6 delegate:(id)arg7;

@end

