//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNItemsDataViewController.h>

#import <T1Twitter/T1OnboardingSearchViewDelegate-Protocol.h>
#import <T1Twitter/T1OnboardingTopicCategoryRowViewDelegate-Protocol.h>
#import <T1Twitter/T1OnboardingTopicViewDelegate-Protocol.h>
#import <T1Twitter/T1OnboardingTopicsSelectorViewControllerDelegate-Protocol.h>
#import <T1Twitter/TFNModalSheetViewControllerDelegate-Protocol.h>

@class NSArray, NSMapTable, NSMutableArray, NSMutableDictionary, NSString, T1FlexibleLayoutView, T1OnboardingHeaderView, T1OnboardingHeaderViewModel, T1OnboardingSearchView, TFNBadgeView, TFNButton, UIActivityIndicatorView;
@protocol T1OnboardingTopicsSelectorViewControllerDelegate;

@interface T1OnboardingTopicsSelectorViewController : TFNItemsDataViewController <T1OnboardingTopicCategoryRowViewDelegate, T1OnboardingTopicsSelectorViewControllerDelegate, T1OnboardingTopicViewDelegate, T1OnboardingSearchViewDelegate, TFNModalSheetViewControllerDelegate>
{
    id <T1OnboardingTopicsSelectorViewControllerDelegate> _delegate;
    _Bool _hasBecomeVisible;
    _Bool _hasBecomeFullyVisible;
    _Bool _hasChangedCategory;
    NSArray *_defaultCategories;
    NSArray *_displayedTopics;
    NSMapTable *_categoryForRowViewTable;
    NSMutableArray *_categoryRowViews;
    NSMutableArray *_selectedTopics;
    NSMutableArray *_cachedSearchTopics;
    NSMutableArray *_topicsSelectedBySearch;
    NSMutableArray *_topicsSelectedInitially;
    NSMutableDictionary *_topicSelectionLocation;
    NSString *_cartDoneLabel;
    NSString *_deselectLabel;
    NSString *_fetchErrorMessage;
    NSString *_searchHint;
    NSString *_selectLabel;
    NSString *_searchDoneLabel;
    T1FlexibleLayoutView *_headerContentContainer;
    T1OnboardingHeaderView *_headerView;
    T1OnboardingHeaderViewModel *_cartHeaderViewModel;
    T1OnboardingHeaderViewModel *_headerViewModel;
    T1OnboardingSearchView *_searchView;
    TFNBadgeView *_cartBadgeView;
    TFNButton *_cartButton;
    UIActivityIndicatorView *_loadingView;
}

- (void).cxx_destruct;
- (id)private_indexAsNumberIfFound:(long long)arg1;
- (CDUnknownBlockType)private_fetchCompletionBlockWithCache:(id)arg1 validation:(CDUnknownBlockType)arg2;
- (void)private_fetchTopics;
- (void)private_addChildRowViewsForCategory:(id)arg1;
- (id)private_generateRowViewForCategory:(id)arg1 level:(long long)arg2;
- (id)private_topicDataItems;
- (id)private_categoryDataItems;
- (void)private_showCartList:(id)arg1;
- (void)private_updateCartButton;
- (_Bool)private_isCartList;
- (_Bool)private_isSearchModeActive;
- (void)private_nextTapped:(id)arg1;
- (void)private_skipTapped:(id)arg1;
- (id)private_toolbarItemsWithNextLabel:(id)arg1 skipLabel:(id)arg2;
- (void)searchViewDidStartEditing:(id)arg1;
- (void)searchViewDidEndEditing:(id)arg1;
- (void)searchView:(id)arg1 didChangeText:(id)arg2;
- (void)topicsSelectorViewController:(id)arg1 didDeselectTopic:(id)arg2 withRowIndex:(id)arg3 location:(long long)arg4;
- (void)topicsSelectorViewController:(id)arg1 didSelectTopic:(id)arg2 withRowIndex:(id)arg3 location:(long long)arg4;
- (id)topicsSelectorViewController:(id)arg1 subtitleForTopic:(id)arg2;
- (id)topicsSelectorViewController:(id)arg1 titleForTopic:(id)arg2;
- (void)topicsSelectorViewController:(id)arg1 fetchTopicsForSearchText:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)topicsSelectorViewController:(id)arg1 fetchTopicsForCategory:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)topicsSelectorViewController:(id)arg1 titleForCategory:(id)arg2;
- (id)topicsSelectorViewController:(id)arg1 childCategoriesForCategory:(id)arg2;
- (void)topicsSelectorViewControllerDidTapSkip:(id)arg1;
- (void)topicsSelectorViewController:(id)arg1 didTapNextWithInitialTopics:(id)arg2 categoryTopics:(id)arg3 searchTopics:(id)arg4;
- (void)topicsSelectorViewControllerDidBecomeVisible:(id)arg1;
- (void)topicViewDidDeselectTopic:(id)arg1;
- (void)topicViewDidSelectTopic:(id)arg1;
- (void)categoryRowViewDidScroll:(id)arg1;
- (void)categoryRowView:(id)arg1 didSelectCategoryWithIndex:(long long)arg2 userInfo:(id)arg3;
- (void)modalSheetViewController:(id)arg1 didPanToCurrentHeight:(double)arg2 preferredHeight:(double)arg3 maximumHeight:(double)arg4 mode:(long long)arg5;
- (double)contentBreakLength;
- (void)update:(_Bool)arg1;
- (long long)tfn_preferredToolbarVisibility;
- (_Bool)tfn_logoTitleViewShown;
- (_Bool)tfn_prefersNavigationBarShadowHidden;
- (void)viewDidFullyAppear:(_Bool)arg1;
- (void)dataViewDidUpdate:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewControllerWillDismissAnimated:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithHeaderViewModel:(id)arg1 cartHeaderViewModel:(id)arg2 nextLabel:(id)arg3 skipLabel:(id)arg4 selectLabel:(id)arg5 deselectLabel:(id)arg6 cartDoneLabel:(id)arg7 searchDoneLabel:(id)arg8 searchHint:(id)arg9 defaultCategories:(id)arg10 selectedTopics:(id)arg11 delegate:(id)arg12;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

