//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/T1ScrollingSegmentedViewControllerDataSource-Protocol.h>

@class NSString, T1GraphQLFeatures, TFNTwitterAccount, TFNTwitterUserDataSource;
@protocol T1ProfileSegmentedFollowingViewControllerDataSourceDelegate;

@interface T1ProfileSegmentedFollowingViewControllerDataSource : NSObject <T1ScrollingSegmentedViewControllerDataSource>
{
    TFNTwitterAccount *_account;
    TFNTwitterUserDataSource *_userDataSource;
    _Bool _showSegmentedFollowersYouKnowViewController;
    _Bool _showSegmentedVerifiedFollowersViewController;
    T1GraphQLFeatures *_graphQLFeatures;
    id <T1ProfileSegmentedFollowingViewControllerDataSourceDelegate> _delegate;
}

+ (_Bool)_t1_isUserDataSource:(id)arg1 protectedFromViewingByAccount:(id)arg2;
+ (id)_t1_followingViewControllerWithUserDataSource:(id)arg1 account:(id)arg2 urtGraphQLTimelineEnabled:(_Bool)arg3 emptyContentMessage:(id)arg4;
+ (id)_t1_followersViewControllerWithUserDataSource:(id)arg1 account:(id)arg2 urtGraphQLTimelineEnabled:(_Bool)arg3 emptyContentMessage:(id)arg4;
+ (id)_t1_verifiedFollowersViewControllerWithUserDataSource:(id)arg1 account:(id)arg2;
+ (id)_t1_friendsFollowingViewControllerWithUserDataSource:(id)arg1 account:(id)arg2;
@property(nonatomic) __weak id <T1ProfileSegmentedFollowingViewControllerDataSourceDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)_t1_followingTimelineEmptyContentMessage;
- (id)_t1_followersTimelineEmptyContentMessage;
- (long long)_t1_segmentTabForIndex:(long long)arg1;
- (long long)segmentIndexForTab:(long long)arg1;
- (id)segmentedViewController:(id)arg1 viewControllerAtIndex:(long long)arg2;
- (id)segmentedViewController:(id)arg1 titleAtIndex:(long long)arg2;
- (long long)numberOfEntriesForSegmentedViewController:(id)arg1;
- (id)initWithTab:(long long)arg1 userDataSource:(id)arg2 account:(id)arg3 showFollowersYouKnow:(_Bool)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

