//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface T1SpheresUserPinnedListsRepository : NSObject
{
    // Error parsing type: , name: account
    // Error parsing type: , name: modelContext
    // Error parsing type: , name: observable
    // Error parsing type: , name: observer
    // Error parsing type: , name: lastObservedValue
    // Error parsing type: , name: legacyModelSupport
    // Error parsing type: , name: delegate
    // Error parsing type: , name: stateArchiver
}

- (void).cxx_destruct;
- (id)init;
- (void)didRemoveAccount:(id)arg1;
- (id)unarchiveSphereViewModels;
- (void)archiveWithSphereViewModels:(id)arg1;
- (id)initWithAccount:(id)arg1 delegate:(id)arg2;

@end

