//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/TFNViewControllerEventObserver-Protocol.h>
#import <T1Twitter/TNLCommunicationAgentObserver-Protocol.h>

@class NSMutableArray, NSNumber, NSString;
@protocol TFSTwitterLegacyScribeLogMethods;

@interface T1StartupReporter : NSObject <TFNViewControllerEventObserver, TNLCommunicationAgentObserver>
{
    long long _waitingState;
    NSNumber *_initialPanelID;
    _Bool _hasLaunched;
    _Bool _hasStayedOnInitialPanelRoot;
    _Bool _hasNetworkRemainedReachable;
    _Bool _isWarmStart;
    _Bool _hasLoggedHomeTimelineDeserializationViewControllerUpdate;
    _Bool _hasLoggedHomeTimelineLoadTop;
    _Bool _hasLoggedHomeTimelineLoadTopViewControllerUpdate;
    _Bool _hasLoggedConnectTimelineInitialized;
    _Bool _validateHomeTimelinePerformanceEventLoggedAfterNextUpdate;
    NSNumber *_homeTimelineDeserializationTimeInterval;
    NSNumber *_homeTimelineDeserializationViewControllerUpdateTimeInterval;
    NSNumber *_homeTimelineLoadTopTimeInterval;
    NSNumber *_homeTimelineLoadTopViewControllerUpdateTimeInterval;
    NSNumber *_connectTimelineInitializedTimeInterval;
    _Bool _hasCompletedStartup;
    NSMutableArray *_startupPerftownLogs;
    NSMutableArray *_startupClientEventLogs;
    id <TFSTwitterLegacyScribeLogMethods> _startupScribe;
    CDUnknownBlockType _scribeAccess;
}

+ (id)sharedReporter;
@property(copy, nonatomic) CDUnknownBlockType scribeAccess; // @synthesize scribeAccess=_scribeAccess;
- (void).cxx_destruct;
- (void)_t1_updateReachabilityWithStatus:(long long)arg1;
- (void)tnl_communicationAgent:(id)arg1 didRegisterObserverWithInitialReachabilityFlags:(unsigned int)arg2 status:(long long)arg3 carrierInfo:(id)arg4 WWANRadioAccessTechnology:(id)arg5 captivePortalStatus:(long long)arg6;
- (void)tnl_communicationAgent:(id)arg1 didUpdateReachabilityFromPreviousFlags:(unsigned int)arg2 previousStatus:(long long)arg3 toCurrentFlags:(unsigned int)arg4 currentStatus:(long long)arg5;
- (void)viewControllerViewWillFullyDisappear:(id)arg1;
- (void)_t1_dataViewControllerDidUpdate:(id)arg1;
- (void)_t1_homeTimelineDidUpdate:(id)arg1;
- (void)_t1_applicationDidBecomeActive:(id)arg1;
- (void)_t1_applicationWillEnterForeground:(id)arg1;
- (void)_t1_applicationDidEnterBackground:(id)arg1;
- (_Bool)_t1_isNetworkReachable:(long long)arg1;
- (void)_t1_performAfterCurrentViewControllerUpdate:(CDUnknownBlockType)arg1;
- (id)_t1_timeInterval;
- (void)_t1_homeTimelineDidUpdateNotification:(id)arg1 getIsFromAPI:(out _Bool *)arg2 hasRealData:(out _Bool *)arg3 hasCompletedApplicationLoadTopRequest:(out _Bool *)arg4;
- (_Bool)_t1_isViewController:(id)arg1 rootOfPanel:(long long)arg2;
- (id)_t1_visibleViewController;
- (long long)_t1_currentPanelID;
- (void)_t1_scribeHomeStartupMetrics;
- (void)_t1_scribeConnectStartupMetrics;
- (void)_t1_scribeAvailableStartupMetrics;
@property(readonly, nonatomic) id <TFSTwitterLegacyScribeLogMethods> scribe;
- (void)flushStartupLoggingToScribe:(id)arg1;
- (void)startupLog:(id)arg1 duration:(double)arg2 eventEndTime:(double)arg3 event:(id)arg4;
- (void)startupLog:(id)arg1 stopwatch:(id)arg2 event:(id)arg3;
- (void)startupLogAction:(id)arg1 element:(id)arg2;
- (void)homeTimelineWillDisplayItem:(id)arg1;
- (void)timelineInitializedForPanel:(long long)arg1;
- (void)didLaunchDirectlyToRoot:(_Bool)arg1 ofPanel:(long long)arg2;
- (void)willLaunch;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

