//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNViewController.h>

@class T1URTViewController, TFNTwitterAccount, TFSTwitterScribeContext;
@protocol T1ThreadTweetsViewControllerDelegate;

@interface T1ThreadTweetsViewController : TFNViewController
{
    id <T1ThreadTweetsViewControllerDelegate> _delegate;
    TFNTwitterAccount *_account;
    TFSTwitterScribeContext *_scribeContext;
    T1URTViewController *_tweetsViewController;
}

@property(retain, nonatomic) T1URTViewController *tweetsViewController; // @synthesize tweetsViewController=_tweetsViewController;
@property(copy, nonatomic) TFSTwitterScribeContext *scribeContext; // @synthesize scribeContext=_scribeContext;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
@property(nonatomic) __weak id <T1ThreadTweetsViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_t1_main_updateNavigationBarItems;
- (void)viewControllerWillPresentAnimated:(_Bool)arg1;
- (id)scribeSection;
- (id)scribePage;
- (void)viewDidLoad;
- (void)_t1_action_didTapDone:(id)arg1;
- (void)_t1_main_updateTweetsViewController;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

