//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionReusableView.h>

#import <T1Twitter/T1UnifiedCardSwipeableCollectionViewCellEventDelegate-Protocol.h>
#import <T1Twitter/UICollectionViewDataSource-Protocol.h>
#import <T1Twitter/UICollectionViewDelegateFlowLayout-Protocol.h>
#import <T1Twitter/UIGestureRecognizerDelegate-Protocol.h>

@class NSDate, NSNumber, NSString, T1UnifiedCardCarouselPageIndicatorView, TFNTwitterUnifiedCardSwipeableMediaComponentModel, TFSTimer, TIPImagePipeline, UICollectionView, UIPanGestureRecognizer, UITapGestureRecognizer;
@protocol T1UnifiedCardCarouselDelegate;

@interface T1UnifiedCardCarouselView : UICollectionReusableView <UIGestureRecognizerDelegate, T1UnifiedCardSwipeableCollectionViewCellEventDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
{
    _Bool _userInteracted;
    _Bool _animationReset;
    double _scrollAnimationPageTime;
    TIPImagePipeline *_imagePipeline;
    double _mediaWidth;
    NSNumber *_mediaLeadingInset;
    UICollectionView *_collectionView;
    TFNTwitterUnifiedCardSwipeableMediaComponentModel *_component;
    id <T1UnifiedCardCarouselDelegate> _delegate;
    T1UnifiedCardCarouselPageIndicatorView *_pageIndicator;
    TFSTimer *_animationDelayTimer;
    UIPanGestureRecognizer *_panRecognizer;
    UITapGestureRecognizer *_scrollingTapRecognizer;
    unsigned long long _lastPageIndex;
    NSDate *_lastScrollInteraction;
}

+ (id)indexCache;
@property(retain, nonatomic) NSDate *lastScrollInteraction; // @synthesize lastScrollInteraction=_lastScrollInteraction;
@property(nonatomic) unsigned long long lastPageIndex; // @synthesize lastPageIndex=_lastPageIndex;
@property(nonatomic) _Bool animationReset; // @synthesize animationReset=_animationReset;
@property(retain, nonatomic) UITapGestureRecognizer *scrollingTapRecognizer; // @synthesize scrollingTapRecognizer=_scrollingTapRecognizer;
@property(retain, nonatomic) UIPanGestureRecognizer *panRecognizer; // @synthesize panRecognizer=_panRecognizer;
@property(retain, nonatomic) TFSTimer *animationDelayTimer; // @synthesize animationDelayTimer=_animationDelayTimer;
@property(nonatomic) _Bool userInteracted; // @synthesize userInteracted=_userInteracted;
@property(retain, nonatomic) T1UnifiedCardCarouselPageIndicatorView *pageIndicator; // @synthesize pageIndicator=_pageIndicator;
@property(nonatomic) __weak id <T1UnifiedCardCarouselDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) TFNTwitterUnifiedCardSwipeableMediaComponentModel *component; // @synthesize component=_component;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) NSNumber *mediaLeadingInset; // @synthesize mediaLeadingInset=_mediaLeadingInset;
@property(nonatomic) double mediaWidth; // @synthesize mediaWidth=_mediaWidth;
@property(retain, nonatomic) TIPImagePipeline *imagePipeline; // @synthesize imagePipeline=_imagePipeline;
@property(nonatomic) double scrollAnimationPageTime; // @synthesize scrollAnimationPageTime=_scrollAnimationPageTime;
- (void).cxx_destruct;
- (double)_t1_fullBleedXOffsetForIndex:(unsigned long long)arg1;
- (void)_t1_scrollToPage:(unsigned long long)arg1 animated:(_Bool)arg2;
- (void)_t1_animateScrolling;
- (void)_t1_animateCardPeek;
- (struct CGRect)_t1_collectionViewFrameAdjustedForSpacing;
- (id)_t1_layoutForCurrentBounds;
- (void)_t1_cancelAnimationDelayTimer;
- (void)_t1_startAffordanceAnimation;
- (void)_t1_handleTap;
- (void)_t1_cancelAutoScroll;
- (void)_t1_handlePanGestureRecognized:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewDidScroll:(id)arg1;
- (void)didLongPressImageOnCell:(id)arg1;
- (void)didTapImageOnCell:(id)arg1;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)prepareForReuse;
- (void)resetAnimation;
- (void)startAffordanceAnimationWithDelay:(double)arg1;
- (void)didDisplay;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
@property(readonly, nonatomic) struct CGSize itemSize;
@property(readonly, nonatomic) unsigned long long currentPageIndex;
@property(readonly, nonatomic) unsigned long long totalPages;
@property(readonly, nonatomic) _Bool animationCancelled;
- (void)layoutSubviews;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)_t1_setupCollectionView;
- (id)initWithFrame:(struct CGRect)arg1 swipeableComponent:(id)arg2 imagePipeline:(id)arg3 delegate:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

