//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNLayoutableView.h>

#import <T1Twitter/T1UnifiedCardComponentView-Protocol.h>

@class NSString, T1AvatarImageView, T1UnifiedCardTwitterListDetailsComponentMemberSubscriberView, TFNAttributedTextView, TFNTappableHighlightView, TFNTwitterUnifiedCard, TFSTwitterScribeContext, TIPImagePipeline, UILabel, UIView;
@protocol T1UnifiedCardComponentViewEventDelegate, TFNTwitterUnifiedCardComponentModel;

@interface T1UnifiedCardTwitterListDetailsComponentView : TFNLayoutableView <T1UnifiedCardComponentView>
{
    TFNTwitterUnifiedCard *_unifiedCard;
    id <TFNTwitterUnifiedCardComponentModel> _component;
    id <T1UnifiedCardComponentViewEventDelegate> _eventDelegate;
    NSString *_accountID;
    TFSTwitterScribeContext *_scribeContext;
    TFNTappableHighlightView *_highlightView;
    UILabel *_titleLabel;
    UILabel *_nameLabel;
    T1UnifiedCardTwitterListDetailsComponentMemberSubscriberView *_memberCountView;
    T1UnifiedCardTwitterListDetailsComponentMemberSubscriberView *_subscriberCountView;
    T1AvatarImageView *_userAvatarImageView;
    TFNAttributedTextView *_userTextView;
}

+ (id)_t1_titleLabelFont;
+ (id)_t1_nameLabelFont;
+ (id)sharedLayoutDelegate;
@property(retain, nonatomic) TFNAttributedTextView *userTextView; // @synthesize userTextView=_userTextView;
@property(retain, nonatomic) T1AvatarImageView *userAvatarImageView; // @synthesize userAvatarImageView=_userAvatarImageView;
@property(retain, nonatomic) T1UnifiedCardTwitterListDetailsComponentMemberSubscriberView *subscriberCountView; // @synthesize subscriberCountView=_subscriberCountView;
@property(retain, nonatomic) T1UnifiedCardTwitterListDetailsComponentMemberSubscriberView *memberCountView; // @synthesize memberCountView=_memberCountView;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) TFNTappableHighlightView *highlightView; // @synthesize highlightView=_highlightView;
@property(copy, nonatomic) TFSTwitterScribeContext *scribeContext; // @synthesize scribeContext=_scribeContext;
@property(copy, nonatomic) NSString *accountID; // @synthesize accountID=_accountID;
@property(nonatomic) __weak id <T1UnifiedCardComponentViewEventDelegate> eventDelegate; // @synthesize eventDelegate=_eventDelegate;
@property(retain, nonatomic) id <TFNTwitterUnifiedCardComponentModel> component; // @synthesize component=_component;
@property(retain, nonatomic) TFNTwitterUnifiedCard *unifiedCard; // @synthesize unifiedCard=_unifiedCard;
- (void).cxx_destruct;
- (void)_t1_didTapListDetails;
- (id)previewingViewControllerForLocation:(struct CGPoint)arg1 outSourceRect:(out struct CGRect *)arg2;
- (void)prepareForReuse;
- (void)setupActions;
- (id)t1_accessibilityCustomActions;
@property(retain, nonatomic) TIPImagePipeline *imagePipeline;
- (id)accessibilityLabel;
@property(readonly, nonatomic) UIView *autoplayableContainerView;
@property(readonly, nonatomic) _Bool shouldDelayContainerTouchDownHighlighting;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

