//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class CAShapeLayer, TFNTwitterUnifiedCardMediaComponentModel;

@interface T1UnifiedCardSwipeableCollectionViewCell : UICollectionViewCell
{
    _Bool _shouldDrawBorders;
    TFNTwitterUnifiedCardMediaComponentModel *_mediaData;
    CAShapeLayer *_borderline;
    long long _position;
}

@property(nonatomic) long long position; // @synthesize position=_position;
@property(nonatomic) _Bool shouldDrawBorders; // @synthesize shouldDrawBorders=_shouldDrawBorders;
@property(retain, nonatomic) CAShapeLayer *borderline; // @synthesize borderline=_borderline;
@property(retain, nonatomic) TFNTwitterUnifiedCardMediaComponentModel *mediaData; // @synthesize mediaData=_mediaData;
- (void).cxx_destruct;
- (struct CGRect)_t1_hairlineAdjustedBounds;
- (const struct CGPath *)_t1_lastElementPath;
- (const struct CGPath *)_t1_firstElementPath;
- (id)_t1_newBorderLayer;
- (id)_t1_newMaskLayer;
- (void)_t1_updateBorderDrawing;
- (void)_t1_updateCornerMask;
- (void)configureSwipeableCollectionViewCellWithData:(id)arg1 imagePipeline:(id)arg2 shouldRenderFullbleed:(_Bool)arg3 cellPosition:(long long)arg4;
- (void)prepareForReuse;
- (void)layoutSublayersOfLayer:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

