//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/T1UnifiedCardSwipeableCollectionViewCell.h>

@class TFNTappableHighlightView, UIImageView;
@protocol T1UnifiedCardSwipeableCollectionViewCellEventDelegate;

@interface T1UnifiedCardSwipeableImageCollectionViewCell : T1UnifiedCardSwipeableCollectionViewCell
{
    id <T1UnifiedCardSwipeableCollectionViewCellEventDelegate> _actionDelegate;
    UIImageView *_imageView;
    TFNTappableHighlightView *_imageHighlightView;
}

@property(retain, nonatomic) TFNTappableHighlightView *imageHighlightView; // @synthesize imageHighlightView=_imageHighlightView;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic) __weak id <T1UnifiedCardSwipeableCollectionViewCellEventDelegate> actionDelegate; // @synthesize actionDelegate=_actionDelegate;
- (void).cxx_destruct;
- (void)configureSwipeableCollectionViewCellWithData:(id)arg1 imagePipeline:(id)arg2 shouldRenderFullbleed:(_Bool)arg3 cellPosition:(long long)arg4;
- (void)_t1_setupActions;
- (void)_t1_didLongPressImage:(id)arg1;
- (void)_t1_didTapImage:(id)arg1;
- (void)_t1_setupImageView;
- (void)_t1_setupHighlightView:(id)arg1 withAccessibilityIdentifier:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

