//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/TAVUIAutoplayFilterPolicy-Protocol.h>
#import <T1Twitter/UIScrollViewDelegate-Protocol.h>

@class NSString, TFNDataViewController, TFSTimer;

@interface TFNAutoplayScrollPolicy : NSObject <TAVUIAutoplayFilterPolicy, UIScrollViewDelegate>
{
    _Bool _isScrollingToTop;
    TFNDataViewController *_dataViewController;
    CDUnknownBlockType _autoplayConditionsDidChangeBlock;
    double _lastScrollSpeedUpdateTime;
    double _scrollSpeed;
    TFSTimer *_autoplayScrollSpeedTimer;
    struct CGPoint _lastContentOffset;
}

@property(retain, nonatomic) TFSTimer *autoplayScrollSpeedTimer; // @synthesize autoplayScrollSpeedTimer=_autoplayScrollSpeedTimer;
@property(nonatomic) double scrollSpeed; // @synthesize scrollSpeed=_scrollSpeed;
@property(nonatomic) double lastScrollSpeedUpdateTime; // @synthesize lastScrollSpeedUpdateTime=_lastScrollSpeedUpdateTime;
@property(nonatomic) struct CGPoint lastContentOffset; // @synthesize lastContentOffset=_lastContentOffset;
@property(nonatomic) _Bool isScrollingToTop; // @synthesize isScrollingToTop=_isScrollingToTop;
@property(copy, nonatomic) CDUnknownBlockType autoplayConditionsDidChangeBlock; // @synthesize autoplayConditionsDidChangeBlock=_autoplayConditionsDidChangeBlock;
@property(nonatomic) __weak TFNDataViewController *dataViewController; // @synthesize dataViewController=_dataViewController;
- (void).cxx_destruct;
- (void)scrollViewDidScrollToTop:(id)arg1;
- (_Bool)scrollViewShouldScrollToTop:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)updateForScrollView;
- (_Bool)autoplayableIsEligibleForAutoplayWithAutoplayable:(id)arg1 activeAutoplayables:(id)arg2;
- (void)didJoinAutoplayPipelineWithAutoplayConditionsDidChangeBlock:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (void)checkScrollSpeed;
- (id)initWithDataViewController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

