//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/NSObject-Protocol.h>

@class NSNumber, NSString, TFSTwitterEntityMedia, TFSTwitterEntitySet, TFSTwitterUserReference;

@protocol TFNDirectMessageUser <NSObject>
@property(nonatomic, readonly) NSString *displayUsername;
@property(nonatomic, readonly) NSString *displayFullName;
@property(nonatomic, readonly) TFSTwitterUserReference *userReference;
@property(nonatomic, readonly) NSNumber *userIDNumber;
@property(nonatomic, readonly) TFSTwitterEntityMedia *profileImageMediaEntity;
@property(nonatomic, readonly) _Bool blocking;
@property(nonatomic, readonly) _Bool verified;
@property(nonatomic, readonly) _Bool protectedUser;
@property(nonatomic, readonly) _Bool following;
@property(nonatomic, readonly) _Bool followRequestSent;
@property(nonatomic, readonly) TFSTwitterEntitySet *bioEntities;
@property(nonatomic, readonly) NSString *bio;
@property(nonatomic, readonly) NSString *fullName;
@property(nonatomic, readonly) NSString *username;
@property(nonatomic, readonly) long long userID;
@end

