//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFSUtilities/TFSConcurrentOperation.h>

#import <T1Twitter/TFNDirectMessageFetchUpdatesOperationDelegate-Protocol.h>

@class NSOperation, NSOperationQueue, TFNDirectMessageFetchUpdatesOperation, TFNDirectMessageInbox, TFNDirectMessageProcessUserUpdatesResponseOperation;

@interface TFNDirectMessageRefreshOperation : TFSConcurrentOperation <TFNDirectMessageFetchUpdatesOperationDelegate>
{
    TFNDirectMessageInbox *_inbox;
    NSOperationQueue *_queue;
    TFNDirectMessageFetchUpdatesOperation *_fetchOperation;
    TFNDirectMessageProcessUserUpdatesResponseOperation *_processResponseOperation;
    NSOperation *_completionOperation;
}

@property(readonly, nonatomic) NSOperation *completionOperation; // @synthesize completionOperation=_completionOperation;
@property(readonly, nonatomic) TFNDirectMessageProcessUserUpdatesResponseOperation *processResponseOperation; // @synthesize processResponseOperation=_processResponseOperation;
@property(readonly, nonatomic) TFNDirectMessageFetchUpdatesOperation *fetchOperation; // @synthesize fetchOperation=_fetchOperation;
@property(retain) NSOperationQueue *queue; // @synthesize queue=_queue;
@property(readonly, nonatomic) TFNDirectMessageInbox *inbox; // @synthesize inbox=_inbox;
- (void).cxx_destruct;
- (void)fetchUpdatesOperation:(id)arg1 didFailWithError:(id)arg2;
- (void)fetchUpdatesOperation:(id)arg1 didSucceedWithResponse:(id)arg2;
- (void)run;
- (void)completeOperation;
- (void)cancel;
- (id)initWithInbox:(id)arg1 model:(id)arg2 source:(long long)arg3 activeConversationID:(id)arg4 filterLowQuality:(id)arg5 includeQuality:(_Bool)arg6;
- (id)init;

@end

