//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/NSObject-Protocol.h>
#import <T1Twitter/TFNReusableViewCacheContainer-Protocol.h>

@class NSIndexPath, TFNDataViewCellLayout, TFNDataViewController, UIView;

@protocol TFNDataViewCell <NSObject, TFNReusableViewCacheContainer>
- (void)didKeyboardSelectInDataViewController:(TFNDataViewController *)arg1 atIndexPath:(NSIndexPath *)arg2;
- (_Bool)isKeyboardSelectable;
@property(nonatomic) _Bool keyboardHighlighted;
- (_Bool)isKeyboardHighlighted;
@property(nonatomic, copy) NSIndexPath *currentIndexPath;
@property(nonatomic, copy) CDUnknownBlockType cleanupBlock;
- (void)cleanup;
@property(nonatomic, copy) CDUnknownBlockType didFirstDisplayInDataViewControllerBlock;
- (void)didFirstDisplayInDataViewController:(TFNDataViewController *)arg1;
@property(nonatomic, copy) CDUnknownBlockType didEndScrollingInDataViewControllerBlock;
@property(nonatomic, copy) CDUnknownBlockType didEndDisplayingInDataViewControllerBlock;
@property(nonatomic, copy) CDUnknownBlockType didDisplayWithZeroVisibilityInDataViewControllerBlock;
@property(nonatomic, copy) CDUnknownBlockType didDisplayInDataViewControllerBlock;
@property(nonatomic, copy) CDUnknownBlockType willDisplayInDataViewControllerBlock;
- (void)didEndScrollingInDataViewController:(TFNDataViewController *)arg1;
- (void)didEndDisplayingInDataViewController:(TFNDataViewController *)arg1 reason:(unsigned long long)arg2;
- (void)didDisplayWithZeroVisibilityInDataViewController:(TFNDataViewController *)arg1 atIndexPath:(NSIndexPath *)arg2;
- (void)didDisplayInDataViewController:(TFNDataViewController *)arg1 atIndexPath:(NSIndexPath *)arg2 visibleIntersection:(struct CGRect)arg3;
- (void)willDisplayInDataViewController:(TFNDataViewController *)arg1 atIndexPath:(NSIndexPath *)arg2;
@property(nonatomic, readonly) UIView *contentView;
@property(nonatomic, readonly) struct CGRect contentFrame;
@property(nonatomic) unsigned long long sectionBreaks;
@property(nonatomic, retain) TFNDataViewCellLayout *cellLayout;

// Remaining properties
@property(nonatomic, readonly) _Bool keyboardSelectable;
@end

