//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFNOnboardingSubtask.h>

@class NSArray, NSDictionary, NSString, TFNOnboardingNavigationLink, TFNOnboardingRichText;

@interface TFNOnboardingTopicsSelectorSubtask : TFNOnboardingSubtask
{
    TFNOnboardingRichText *_primaryText;
    TFNOnboardingRichText *_secondaryText;
    NSArray *_topCategoryIDs;
    NSArray *_defaultCategoryIDs;
    NSDictionary *_categoryByIDList;
    NSDictionary *_topicByIDList;
    NSString *_searchHint;
    TFNOnboardingRichText *_searchDoneLabel;
    TFNOnboardingRichText *_bannerTitle;
    TFNOnboardingRichText *_bannerSubtitle;
    TFNOnboardingRichText *_bannerDismissLabel;
    TFNOnboardingRichText *_cartTitle;
    TFNOnboardingRichText *_cartDoneLabel;
    NSArray *_selectedTopicIDs;
    TFNOnboardingRichText *_selectLabel;
    TFNOnboardingRichText *_deselectLabel;
    TFNOnboardingNavigationLink *_nextLink;
    TFNOnboardingNavigationLink *_skipLink;
}

+ (long long)version;
+ (id)typeNames;
@property(readonly, nonatomic) TFNOnboardingNavigationLink *skipLink; // @synthesize skipLink=_skipLink;
@property(readonly, nonatomic) TFNOnboardingNavigationLink *nextLink; // @synthesize nextLink=_nextLink;
@property(readonly, nonatomic) TFNOnboardingRichText *deselectLabel; // @synthesize deselectLabel=_deselectLabel;
@property(readonly, nonatomic) TFNOnboardingRichText *selectLabel; // @synthesize selectLabel=_selectLabel;
@property(readonly, nonatomic) NSArray *selectedTopicIDs; // @synthesize selectedTopicIDs=_selectedTopicIDs;
@property(readonly, nonatomic) TFNOnboardingRichText *cartDoneLabel; // @synthesize cartDoneLabel=_cartDoneLabel;
@property(readonly, nonatomic) TFNOnboardingRichText *cartTitle; // @synthesize cartTitle=_cartTitle;
@property(readonly, nonatomic) TFNOnboardingRichText *bannerDismissLabel; // @synthesize bannerDismissLabel=_bannerDismissLabel;
@property(readonly, nonatomic) TFNOnboardingRichText *bannerSubtitle; // @synthesize bannerSubtitle=_bannerSubtitle;
@property(readonly, nonatomic) TFNOnboardingRichText *bannerTitle; // @synthesize bannerTitle=_bannerTitle;
@property(readonly, nonatomic) TFNOnboardingRichText *searchDoneLabel; // @synthesize searchDoneLabel=_searchDoneLabel;
@property(readonly, nonatomic) NSString *searchHint; // @synthesize searchHint=_searchHint;
@property(readonly, nonatomic) NSDictionary *topicByIDList; // @synthesize topicByIDList=_topicByIDList;
@property(readonly, nonatomic) NSDictionary *categoryByIDList; // @synthesize categoryByIDList=_categoryByIDList;
@property(readonly, nonatomic) NSArray *defaultCategoryIDs; // @synthesize defaultCategoryIDs=_defaultCategoryIDs;
@property(readonly, nonatomic) NSArray *topCategoryIDs; // @synthesize topCategoryIDs=_topCategoryIDs;
@property(readonly, nonatomic) TFNOnboardingRichText *secondaryText; // @synthesize secondaryText=_secondaryText;
@property(readonly, nonatomic) TFNOnboardingRichText *primaryText; // @synthesize primaryText=_primaryText;
- (void).cxx_destruct;
- (id)initWithJSONDictionary:(id)arg1 subtaskID:(id)arg2 typeName:(id)arg3 backNavigationType:(long long)arg4 backNavigationLink:(id)arg5 error:(id *)arg6;

@end

