//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFNOnboardingSubtask.h>

@class NSArray, NSString, TFNOnboardingNavigationLink, TFNOnboardingRichText, TFNOnboardingSettingsValue;

@interface TFNOnboardingEnterPhoneSubtask : TFNOnboardingSubtask
{
    TFNOnboardingRichText *_primaryText;
    TFNOnboardingRichText *_secondaryText;
    NSString *_hintText;
    TFNOnboardingNavigationLink *_nextLink;
    TFNOnboardingNavigationLink *_skipLink;
    NSArray *_countryCodes;
    NSString *_defaultCountryCode;
    TFNOnboardingSettingsValue *_discoverabilitySetting;
}

+ (id)countryCodeSubtaskDataKey;
+ (id)phoneNumberSubtaskDataKey;
+ (long long)version;
+ (id)typeNames;
@property(readonly, nonatomic) TFNOnboardingSettingsValue *discoverabilitySetting; // @synthesize discoverabilitySetting=_discoverabilitySetting;
@property(readonly, nonatomic) NSString *defaultCountryCode; // @synthesize defaultCountryCode=_defaultCountryCode;
@property(readonly, nonatomic) NSArray *countryCodes; // @synthesize countryCodes=_countryCodes;
@property(readonly, nonatomic) TFNOnboardingNavigationLink *skipLink; // @synthesize skipLink=_skipLink;
@property(readonly, nonatomic) TFNOnboardingNavigationLink *nextLink; // @synthesize nextLink=_nextLink;
@property(readonly, nonatomic) NSString *hintText; // @synthesize hintText=_hintText;
@property(readonly, nonatomic) TFNOnboardingRichText *secondaryText; // @synthesize secondaryText=_secondaryText;
@property(readonly, nonatomic) TFNOnboardingRichText *primaryText; // @synthesize primaryText=_primaryText;
- (void).cxx_destruct;
- (id)initWithJSONDictionary:(id)arg1 subtaskID:(id)arg2 typeName:(id)arg3 backNavigationType:(long long)arg4 backNavigationLink:(id)arg5 error:(id *)arg6;

@end

