//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFNOnboardingSubtask.h>

@class NSArray, NSString, TFNOnboardingNavigationLink, TFNOnboardingRichText, TFNPeopleDiscoveryShowMore;

@interface TFNOnboardingSettingsListSubtask : TFNOnboardingSubtask
{
    _Bool _shouldDisplayCellBorders;
    NSArray *_settings;
    TFNOnboardingRichText *_primaryText;
    TFNOnboardingRichText *_secondaryText;
    TFNOnboardingRichText *_detailText;
    TFNOnboardingNavigationLink *_nextLink;
    NSString *_scrollHint;
    TFNPeopleDiscoveryShowMore *_showMore;
}

+ (long long)version;
+ (id)typeNames;
@property(readonly, nonatomic) _Bool shouldDisplayCellBorders; // @synthesize shouldDisplayCellBorders=_shouldDisplayCellBorders;
@property(readonly, nonatomic) TFNPeopleDiscoveryShowMore *showMore; // @synthesize showMore=_showMore;
@property(readonly, nonatomic) NSString *scrollHint; // @synthesize scrollHint=_scrollHint;
@property(readonly, nonatomic) TFNOnboardingNavigationLink *nextLink; // @synthesize nextLink=_nextLink;
@property(readonly, nonatomic) TFNOnboardingRichText *detailText; // @synthesize detailText=_detailText;
@property(readonly, nonatomic) TFNOnboardingRichText *secondaryText; // @synthesize secondaryText=_secondaryText;
@property(readonly, nonatomic) TFNOnboardingRichText *primaryText; // @synthesize primaryText=_primaryText;
@property(readonly, nonatomic) NSArray *settings; // @synthesize settings=_settings;
- (void).cxx_destruct;
- (id)initWithJSONDictionary:(id)arg1 subtaskID:(id)arg2 typeName:(id)arg3 backNavigationType:(long long)arg4 backNavigationLink:(id)arg5 error:(id *)arg6;

@end

