//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString, TFNOnboardingRichText;

@interface TFNOnboardingTopicCategory : NSObject
{
    NSString *_identifier;
    TFNOnboardingRichText *_title;
    NSArray *_subcategoryIDs;
    NSArray *_topicIDs;
}

@property(readonly, nonatomic) NSArray *topicIDs; // @synthesize topicIDs=_topicIDs;
@property(readonly, nonatomic) NSArray *subcategoryIDs; // @synthesize subcategoryIDs=_subcategoryIDs;
@property(readonly, nonatomic) TFNOnboardingRichText *title; // @synthesize title=_title;
@property(readonly, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (id)initWithJSONDictionary:(id)arg1 error:(id *)arg2;

@end

