//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFNOnboardingIdentityVerificationSubtask.h>

@class NSString, TFNOnboardingSubtaskDataReference;

@interface TFNOnboardingPhoneVerificationSubtask : TFNOnboardingIdentityVerificationSubtask
{
    _Bool _sendViaVoice;
    NSString *_phoneNumberString;
    TFNOnboardingSubtaskDataReference *_phoneNumberSubtaskDataReference;
    NSString *_countryCodeString;
    TFNOnboardingSubtaskDataReference *_countryCodeSubtaskDataReference;
}

+ (long long)version;
+ (id)resendVoiceNavigationContextAction;
+ (id)resendSMSNavigationContextAction;
+ (id)typeNames;
@property(readonly, nonatomic) _Bool sendViaVoice; // @synthesize sendViaVoice=_sendViaVoice;
@property(readonly, nonatomic) TFNOnboardingSubtaskDataReference *countryCodeSubtaskDataReference; // @synthesize countryCodeSubtaskDataReference=_countryCodeSubtaskDataReference;
@property(readonly, nonatomic) NSString *countryCodeString; // @synthesize countryCodeString=_countryCodeString;
@property(readonly, nonatomic) TFNOnboardingSubtaskDataReference *phoneNumberSubtaskDataReference; // @synthesize phoneNumberSubtaskDataReference=_phoneNumberSubtaskDataReference;
@property(readonly, nonatomic) NSString *phoneNumberString; // @synthesize phoneNumberString=_phoneNumberString;
- (void).cxx_destruct;
- (id)initWithJSONDictionary:(id)arg1 subtaskID:(id)arg2 typeName:(id)arg3 backNavigationType:(long long)arg4 backNavigationLink:(id)arg5 error:(id *)arg6;

@end

