//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TFNTwitterDeviceFeatureSwitches : NSObject
{
}

+ (_Bool)isNewsCameraStatusesUploadEndpointEnabled;
+ (id)blacklistedPeriscopeURLDestinations;
+ (_Bool)isHighlightedLabelRequestParameterEnabled;
+ (double)stratoHashflagsRefreshInterval;
+ (_Bool)limitBufferingAggressivelyOnPausedItems;
+ (_Bool)limitBufferingOnAllPlayerItems;
+ (id)preWarmConnectionHostNames;
+ (unsigned long long)maxNumberDiscountedURLs;
+ (_Bool)isDisplayTextModelEnabled;
+ (id)_featureSwitches;
+ (long long)tpmIdSyncClickIntervalInSeconds;
+ (long long)tpmIdSyncFetchIntervalInSeconds;
+ (_Bool)isDeferingAccountAndUserUpdateNotificationEnabled;
+ (long long)backgroundTaskExpirationReportingThreshold;
+ (_Bool)isGraphQLStatusesShowDarkReadEnabled;
+ (_Bool)isGraphQLStatusesShowEnabled;
+ (_Bool)isGraphQLAccountVerifyCredentialsEnabled;
+ (_Bool)isGraphQLUsersShowEnabled;
+ (_Bool)coreServices2UserBuilderEnabled;
+ (id)coreServices2TNLBackgroundIdleTimeout;
+ (id)coreServices2TNLForegroundIdleTimeout;
+ (unsigned long long)maximumFullNameLength;
+ (long long)scribeAPIErrorSampleSize;
+ (long long)scribeAPISampleSize;
+ (id)httpHostMapArray;
+ (_Bool)isOAuthScopeBackendEnabled;
+ (_Bool)isTeamsAccountUIEnabled;
+ (_Bool)isTeamsAccountEnabled;
+ (id)optionalSetForKey:(id)arg1;
+ (id)requiredSetForKey:(id)arg1;
+ (void)setIsFeatureSwitchSetCachingEnabled:(_Bool)arg1;
+ (_Bool)isFeatureSwitchSetCachingEnabled;
+ (id)shouldUseSetCachingQueue;
+ (void)accessFeatureSwitchValueOnce:(long long *)arg1 valueAccessBlock:(CDUnknownBlockType)arg2;
+ (long long)appSplitNewsCameraSwipeAngle;
+ (_Bool)isDashOpenOnLongPressBackEnabled;
+ (_Bool)isDashContentSFSVCEnabled;
+ (_Bool)isBetaBugButtonEmailFlowEnabled;
+ (_Bool)isTNLForPeriscopePluginEnabled;
+ (id)nonFatalSecurityBlacklist;
+ (id)dataSensitiveCountries;
+ (id)dataInsensitiveCountries;
+ (id)foundMediaDomains;
+ (id)CDNFileExtensionList;
+ (id)CDNHostRootList;
+ (long long)CDNSampleSize;
+ (_Bool)isOnboardingFormsBasedSettingsListSubtaskEnabled;
+ (_Bool)isOnboardingPreferredLanguageSelectorEnabled;
+ (_Bool)isOnboardingNotificationsBackstopPromptEnabled;
+ (_Bool)isOnboardingLocationBackstopPromptEnabled;
+ (id)appEventTrackingShortenedTrackingParameters;
+ (double)appEventTrackingNonReferredOpenInterval;
+ (_Bool)isExternalURLProtectionEnabled;
+ (id)bouncerWhitelistAll;
+ (id)bouncerWhitelistEntrances;
+ (_Bool)isPublicInterestInterstitialEnabled;
+ (_Bool)isMultiAccountIdentityEnabled;
+ (_Bool)isMultiAccountIncentiveEnabled;
+ (_Bool)isLoginJSInstrumentationEnabled;
+ (id)phoneSignupCountriesNotificationsWhitelist;
+ (id)phoneSignupCountriesBlacklist;
+ (id)phoneSignupCountriesGraylist;
+ (_Bool)usePushPayloadsForComponentBadgeCounts;
+ (_Bool)isAggregateBadgingInPushEnabled;
+ (double)ambientNotificationCooldownPeriod;
+ (long long)maxQueuedAmbientNotifications;
+ (long long)rightToLeftMode;
+ (_Bool)isFeatureSwitchesCrashlyticsLoggingEnabled;
+ (long long)appStoreReviewPromptDaysAfterCrashMin;
+ (long long)appStoreReviewPromptDaysBetweenAttemptsMin;
+ (long long)appStoreReviewPromptConsecutiveDaysMin;
+ (_Bool)isAppStoreReviewShowPromptAfterFavoriteEnabled;
+ (_Bool)isAppStoreReviewShowPromptAfterTweetEnabled;
+ (_Bool)isAppStoreReviewShowPromptOnStartupEnabled;
+ (id)private_redactionListForKey:(id)arg1 defaultList:(id)arg2;
+ (id)protectedStatusKeysRedactionList;
+ (id)protectedUserKeysRedactionList;
+ (id)HTTPHeaderFieldRedactionList;
+ (id)userDefaultsKeysRedactionList;
+ (_Bool)isSpotlightBackgroundFetchEnabled;
+ (double)homeTimelineBackgroundFetchSinceBackgroundThreshold;
+ (double)homeTimelineBackgroundFetchLongRefreshThreshold;
+ (double)homeTimelineBackgroundFetchLaunchThreshold;
+ (double)homeTimelineBackgroundFetchUILaunchDelay;
+ (double)homeTimelineBackgroundFetchUpdateTime;
+ (_Bool)isHomeTimelineBackgroundFetchEnabled;
+ (_Bool)isModalSheetsSlideoverEnabledForTweetDrafts;
+ (_Bool)isModalSheetsComposerUnificationSlideoverEnabled;
+ (double)_CGFloatForKey:(id)arg1 minValue:(double)arg2 maxValue:(double)arg3;
+ (long long)_integerForKey:(id)arg1 minValue:(long long)arg2 maxValue:(long long)arg3;
+ (id)nonUsernamePaths;
+ (long long)mediaURLLength;
+ (long long)shortenedURLLengthSecure;
+ (id)blackListedWebViewDomains;
+ (id)blackListedEmailDomains;
+ (double)scribeStatusLingerMaxThresholdInSeconds;
+ (double)scribeStatusLingerMinThresholdInSeconds;
+ (long long)typeaheadMaxUserMatches;
+ (long long)typeaheadMaxRecentSearchesHorizontallyScrolling;
+ (long long)typeaheadMaxRecentSearches;
+ (long long)typeaheadMaxQueryMatches;
+ (long long)typeaheadUserPrefetchSize;
+ (double)typeaheadUserPrefetchRateInSeconds;
+ (long long)antispamQueryFrequency;
+ (long long)antispamConnectUserCount;
+ (long long)antispamConnectTweetCount;
+ (_Bool)disableInlinePhotosInstagram;
+ (_Bool)disableWatchdogDetection;
+ (_Bool)shouldScribeCrash;
+ (_Bool)shouldScribeError;
+ (_Bool)isKeyboardCellSelectionEnabled;
+ (_Bool)isSmartInvertColorsEnabled;
+ (_Bool)isNestedActionButtonEnabled;
+ (_Bool)isLargeScreenLayoutExtendedContentEnabled;
+ (_Bool)isLargeScreenLayoutSpecializationEnabled;
+ (_Bool)isContextMenuPreviewingEnabled;
+ (_Bool)is3DTouchPreviewingEnabled;
+ (_Bool)isUNUserNotificationCenterEnabled;

@end

