//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFNTwitterUnifiedCardBaseComponentModel.h>

#import <T1Twitter/TFNTwitterUnifiedCardDetailsAdaptable-Protocol.h>

@class NSArray, NSString, TFNTwitterUnifiedCardAppStoreDataEntryPlatformMap, TFNTwitterUnifiedCardDestinationModel;

@interface TFNTwitterUnifiedCardAppStoreDetailsComponentModel : TFNTwitterUnifiedCardBaseComponentModel <TFNTwitterUnifiedCardDetailsAdaptable>
{
    TFNTwitterUnifiedCardAppStoreDataEntryPlatformMap *_platformMap;
}

+ (id)componentWithJSON:(id)arg1 destinationDict:(id)arg2 mediaEntitiesDict:(id)arg3 appStoreData:(id)arg4 promotedContent:(id)arg5 usersDict:(id)arg6;
@property(retain, nonatomic) TFNTwitterUnifiedCardAppStoreDataEntryPlatformMap *platformMap; // @synthesize platformMap=_platformMap;
- (void).cxx_destruct;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
@property(readonly, nonatomic) _Bool isSubtitleRTL;
@property(readonly, nonatomic) _Bool isTitleRTL;
@property(readonly, copy, nonatomic) NSString *subtitle;
@property(readonly, copy, nonatomic) NSString *title;
@property(readonly, nonatomic) unsigned long long type;
- (id)initWithComponentJSON:(id)arg1 destinationDict:(id)arg2 platformMap:(id)arg3;
- (id)withPromotedContent:(id)arg1;

// Remaining properties
@property(readonly, nonatomic) NSArray *axDestinations;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) TFNTwitterUnifiedCardDestinationModel *destination;
@property(readonly, nonatomic) _Bool shouldRenderFullBleed;
@property(readonly) Class superclass;

@end

