//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/TFSTwitterTypeaheadServiceLookupWorker-Protocol.h>

@class NSString, TFSModelContext;

@interface TFNTwitterTypeaheadConcreteLookupWorker : NSObject <TFSTwitterTypeaheadServiceLookupWorker>
{
    NSString *_accountID;
    TFSModelContext *_modelContext;
}

@property(readonly, nonatomic) TFSModelContext *modelContext; // @synthesize modelContext=_modelContext;
@property(readonly, copy, nonatomic) NSString *accountID; // @synthesize accountID=_accountID;
- (void).cxx_destruct;
- (id)startWithQuery:(id)arg1 resultType:(long long)arg2 sourceType:(unsigned long long)arg3 geoRequestFilter:(_Bool)arg4 contextText:(id)arg5 topicType:(unsigned long long)arg6 completion:(CDUnknownBlockType)arg7;
- (id)initWithAccountID:(id)arg1 modelContext:(id)arg2;

@end

