//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSString, TFSModelIdentifier;

@protocol TFSTwitterTypeaheadServiceLookupWorker
- (TFSModelIdentifier *)startWithQuery:(NSString *)arg1 resultType:(long long)arg2 sourceType:(unsigned long long)arg3 geoRequestFilter:(_Bool)arg4 contextText:(NSString *)arg5 topicType:(unsigned long long)arg6 completion:(void (^)(_Bool, id, NSError *))arg7;
@end

